BUILD := build
EFI := $(BUILD)/BOOTX64.EFI
KERNEL := $(BUILD)/KERNEL.ELF
ROOTFS_DIR := rootfs
ROOTFS := $(BUILD)/ROOTFS.TAR
USER_ELF_TEST := $(ROOTFS_DIR)/bin/elftest.elf
USER_SUPERVISOR := $(ROOTFS_DIR)/bin/supervisor.elf
USER_WORKER_SERVICE := $(ROOTFS_DIR)/bin/workerservice.elf
USER_ORDINARY_SERVICE := $(ROOTFS_DIR)/bin/ordinaryservice.elf
USER_ORDINARY_SERVICE_REPLACEMENT := $(ROOTFS_DIR)/bin/ordinaryservice-v2.elf
USER_CONSOLE_SERVICE := $(ROOTFS_DIR)/bin/consoleservice.elf
USER_HELLO := $(ROOTFS_DIR)/bin/hello.elf
USER_INPUT_ECHO := $(ROOTFS_DIR)/bin/inputecho.elf
USER_LAUNCH_PROBE := $(ROOTFS_DIR)/bin/launchprobe.elf
USER_RUNTIME_TEST := $(ROOTFS_DIR)/bin/runtimetest.elf
USER_RUNTIME_CANCEL_TEST := $(ROOTFS_DIR)/bin/runtimecanceltest.elf
USER_RUNTIME_BLOCK_TEST := $(ROOTFS_DIR)/bin/runtimeblocktest.elf
USER_DISPLAY_SERVICE := $(ROOTFS_DIR)/bin/displayservice.elf
USER_COMPOSITOR_SERVICE := $(ROOTFS_DIR)/bin/compositorservice.elf
USER_SURFACE_APP := $(ROOTFS_DIR)/bin/surfaceapp.elf
USER_MEDIA_PLAYER := $(ROOTFS_DIR)/bin/mediaplayer.elf
.DEFAULT_GOAL := all
.DELETE_ON_ERROR:

USER_PROGRAMS := $(USER_ELF_TEST) $(USER_SUPERVISOR) $(USER_WORKER_SERVICE) $(USER_ORDINARY_SERVICE) $(USER_ORDINARY_SERVICE_REPLACEMENT) $(USER_CONSOLE_SERVICE) $(USER_HELLO) $(USER_INPUT_ECHO) $(USER_LAUNCH_PROBE) $(USER_RUNTIME_TEST) $(USER_RUNTIME_BLOCK_TEST) $(USER_RUNTIME_CANCEL_TEST) $(USER_DISPLAY_SERVICE) $(USER_COMPOSITOR_SERVICE) $(USER_SURFACE_APP) $(USER_MEDIA_PLAYER)
ROOTFS_FILES := $(shell test -d $(ROOTFS_DIR) && find $(ROOTFS_DIR) -type f)
IMAGE := $(BUILD)/JA-os.img

CLANG ?= clang
LLD_LINK ?= lld-link
LD := ld.lld
NASM ?= nasm
PYTHON ?= python
FFMPEG ?= ffmpeg
READELF ?= llvm-readelf
OBJDUMP ?= llvm-objdump
QEMU ?= qemu-system-x86_64
FRAMEBUFFER_WIDTH ?= 0
FRAMEBUFFER_HEIGHT ?= 0
OVMF_CODE ?= /mingw64/share/qemu/edk2-x86_64-code.fd
OVMF_VARS ?= /mingw64/share/qemu/edk2-i386-vars.fd

# A successful inspection is required; tool failure is not a clean ELF report.
define CHECK_ELF_RELOCATIONS
	@set -eu; \
	if ! relocations="$$(LC_ALL=C $(READELF) -r "$@")"; then \
		echo "Failed to inspect ELF relocations: $@" >&2; \
		exit 1; \
	fi; \
	case "$$relocations" in \
		*R_X86_64*) \
			printf '%s\n' "$$relocations"; \
			echo "Runtime relocations are unsupported: $@" >&2; \
			exit 1 ;; \
		'') \
			echo "No ELF relocations: $@" ;; \
	esac
endef

$(BUILD)/user_elftest.o: user/elftest.S include/user_abi.h | $(BUILD)
	$(CLANG) --target=x86_64-unknown-none-elf -c $< -o $@

$(USER_ELF_TEST): $(BUILD)/user_elftest.o user/elftest.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/elftest.ld \
	      -o $@ $(BUILD)/user_elftest.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_crt0.o: user/crt0.S | $(BUILD)
	$(CLANG) --target=x86_64-unknown-none-elf -c $< -o $@

$(BUILD)/user_crt0_startup.o: user/crt0_startup.S include/program_startup.h include/user_abi.h | $(BUILD)
	$(CLANG) --target=x86_64-unknown-none-elf -c $< -o $@

$(BUILD)/user_syscall.o: user/lib/syscall.S include/user_abi.h | $(BUILD)
	$(CLANG) --target=x86_64-unknown-none-elf -c $< -o $@

$(BUILD)/user_supervisor.o: user/supervisor.c \
                            user/lib/syscall.h \
                            include/user_abi.h \
                            include/program_startup.h \
                            include/supervisor_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_SUPERVISOR): $(BUILD)/user_crt0_startup.o \
                    $(BUILD)/user_syscall.o \
                    $(BUILD)/user_supervisor.o \
                    user/supervisor.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/supervisor.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_supervisor.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_worker_service.o: user/worker_service.c \
                                user/lib/syscall.h \
                                include/user_abi.h \
                                include/program_startup.h \
                                include/worker_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_WORKER_SERVICE): $(BUILD)/user_crt0_startup.o \
                        $(BUILD)/user_syscall.o \
                        $(BUILD)/user_worker_service.o \
                        user/worker_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/worker_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_worker_service.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_ordinary_service.o: user/ordinary_service.c \
                                  user/lib/syscall.h \
                                  include/user_abi.h \
                                  include/program_startup.h \
                                  include/service_protocol.h \
                                  include/ordinary_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_ORDINARY_SERVICE): $(BUILD)/user_crt0_startup.o \
                          $(BUILD)/user_syscall.o \
                          $(BUILD)/user_ordinary_service.o \
                          user/ordinary_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/ordinary_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_ordinary_service.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_ordinary_service_replacement.o: user/ordinary_service.c \
                                              user/lib/syscall.h \
                                              include/user_abi.h \
                                              include/program_startup.h \
                                              include/service_protocol.h \
                                              include/ordinary_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) \
	      -DJCOS_ORDINARY_SERVICE_IMAGE_ID=JCOS_ORDINARY_SERVICE_IMAGE_REPLACEMENT \
	      -c $< -o $@

$(USER_ORDINARY_SERVICE_REPLACEMENT): $(BUILD)/user_crt0_startup.o \
                                      $(BUILD)/user_syscall.o \
                                      $(BUILD)/user_ordinary_service_replacement.o \
                                      user/ordinary_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/ordinary_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_ordinary_service_replacement.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_display_service.o: user/display_service.c \
                                 user/lib/syscall.h \
                                 include/user_abi.h \
                                 include/program_startup.h \
                                 include/service_protocol.h \
                                 include/display_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_DISPLAY_SERVICE): $(BUILD)/user_crt0_startup.o \
                         $(BUILD)/user_syscall.o \
                         $(BUILD)/user_display_service.o \
                         user/display_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/display_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_display_service.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_compositor_service.o: user/compositor_service.c \
                                    user/lib/syscall.h \
                                    include/user_abi.h \
                                    include/program_startup.h \
                                    include/service_protocol.h \
                                    include/display_service_protocol.h \
                                    include/compositor_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_COMPOSITOR_SERVICE): $(BUILD)/user_crt0_startup.o \
                            $(BUILD)/user_syscall.o \
                            $(BUILD)/user_compositor_service.o \
                            user/compositor_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/compositor_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_compositor_service.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_surface_app.o: user/surface_app.c \
                             user/lib/syscall.h \
                             include/user_abi.h \
                             include/program_startup.h \
                             include/display_service_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_SURFACE_APP): $(BUILD)/user_crt0_startup.o \
                     $(BUILD)/user_syscall.o \
                     $(BUILD)/user_surface_app.o \
                     user/surface_app.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/surface_app.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_surface_app.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_boot_archive.o: user/lib/boot_archive.c \
                                user/lib/boot_archive.h \
                                user/lib/syscall.h \
                                include/user_abi.h \
                                include/boot_archive_portal_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(BUILD)/user_console_service.o: user/console_service.c \
                                 user/lib/boot_archive.h \
                                 user/lib/syscall.h \
                                 include/user_abi.h \
                                 include/program_startup.h \
                                 include/service_protocol.h \
                                 include/console_portal_abi.h \
                                 include/console_client_protocol.h \
                                 include/console_input_protocol.h \
                                 include/console_service_protocol.h \
                                 include/boot_archive_portal_abi.h \
                                 include/program_broker_protocol.h \
                                 include/service_broker_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_CONSOLE_SERVICE): $(BUILD)/user_crt0_startup.o \
                         $(BUILD)/user_syscall.o \
                         $(BUILD)/user_boot_archive.o \
                         $(BUILD)/user_console_service.o \
                         user/console_service.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/console_service.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_boot_archive.o \
	      $(BUILD)/user_console_service.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_console_client.o: user/lib/console.c \
                                user/lib/console.h \
                                user/lib/syscall.h \
                                include/user_abi.h \
                                include/console_client_protocol.h \
                                include/console_input_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(BUILD)/user_hello.o: user/hello.c \
                        user/lib/console.h \
                        user/lib/syscall.h \
                        include/user_abi.h \
                        include/program_startup.h \
                        include/console_client_protocol.h \
                        include/console_input_protocol.h \
                        include/hello_app_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_HELLO): $(BUILD)/user_crt0_startup.o \
               $(BUILD)/user_syscall.o \
               $(BUILD)/user_console_client.o \
               $(BUILD)/user_hello.o \
               user/hello.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/hello.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_console_client.o \
	      $(BUILD)/user_hello.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_input_echo.o: user/input_echo.c \
                             user/lib/console.h \
                             user/lib/syscall.h \
                             include/user_abi.h \
                             include/program_startup.h \
                             include/console_client_protocol.h \
                             include/console_input_protocol.h \
                             include/input_echo_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_INPUT_ECHO): $(BUILD)/user_crt0_startup.o \
                     $(BUILD)/user_syscall.o \
                     $(BUILD)/user_console_client.o \
                     $(BUILD)/user_input_echo.o \
                     user/input_echo.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/input_echo.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_console_client.o \
	      $(BUILD)/user_input_echo.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_media_player.o: user/media_player.c \
                              user/lib/console.h \
                              user/lib/syscall.h \
                              include/user_abi.h \
                              include/program_startup.h \
                              include/console_client_protocol.h \
                              include/media_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_MEDIA_PLAYER): $(BUILD)/user_crt0_startup.o \
                      $(BUILD)/user_syscall.o \
                      $(BUILD)/user_console_client.o \
                      $(BUILD)/user_media_player.o \
                      user/media_player.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/media_player.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_console_client.o \
	      $(BUILD)/user_media_player.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_launch_probe.o: user/launch_probe.c \
                              user/lib/syscall.h \
                              include/user_abi.h \
                              include/program_startup.h \
                              include/launch_probe_protocol.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(USER_LAUNCH_PROBE): $(BUILD)/user_crt0_startup.o \
                      $(BUILD)/user_syscall.o \
                      $(BUILD)/user_launch_probe.o \
                      user/launch_probe.ld Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/launch_probe.ld \
	      -o $@ \
	      $(BUILD)/user_crt0_startup.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_launch_probe.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_runtime_test.o: user/runtime_test.c \
                              user/lib/syscall.h \
                              include/user_abi.h \
                              include/runtime_test_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@

$(BUILD)/user_runtime_cancel_test.o: \
        user/runtime_cancel_test.c \
        user/lib/syscall.h \
        include/user_abi.h \
        include/runtime_cancel_test_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@


$(USER_RUNTIME_CANCEL_TEST): \
        $(BUILD)/user_crt0.o \
        $(BUILD)/user_syscall.o \
        $(BUILD)/user_runtime_cancel_test.o \
        user/runtime_cancel_test.ld \
        Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/runtime_cancel_test.ld \
	      -o $@ \
	      $(BUILD)/user_crt0.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_runtime_cancel_test.o
	$(CHECK_ELF_RELOCATIONS)

$(BUILD)/user_runtime_block_probe.o: \
        user/runtime_block_probe.S \
        include/runtime_block_test_abi.h \
        include/user_abi.h | $(BUILD)
	$(CLANG) --target=x86_64-unknown-none-elf -c $< -o $@


$(BUILD)/user_runtime_block_test.o: \
        user/runtime_block_test.c \
        user/lib/syscall.h \
        include/user_abi.h \
        include/runtime_block_test_abi.h | $(BUILD)
	$(CLANG) $(USER_CFLAGS) -c $< -o $@


$(USER_RUNTIME_BLOCK_TEST): \
        $(BUILD)/user_crt0.o \
        $(BUILD)/user_syscall.o \
        $(BUILD)/user_runtime_block_probe.o \
        $(BUILD)/user_runtime_block_test.o \
        user/runtime_block_test.ld \
        Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/runtime_block_test.ld \
	      -o $@ \
	      $(BUILD)/user_crt0.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_runtime_block_probe.o \
	      $(BUILD)/user_runtime_block_test.o
	$(CHECK_ELF_RELOCATIONS)

$(USER_RUNTIME_TEST): $(BUILD)/user_crt0.o \
                      $(BUILD)/user_syscall.o \
                      $(BUILD)/user_runtime_test.o \
                      user/runtime_test.ld \
                      Makefile.msys2
	mkdir -p $(dir $@)
	$(LD) -m elf_x86_64 -nostdlib -static \
	      -T user/runtime_test.ld \
	      -o $@ \
	      $(BUILD)/user_crt0.o \
	      $(BUILD)/user_syscall.o \
	      $(BUILD)/user_runtime_test.o
	$(CHECK_ELF_RELOCATIONS)

MEDIA_DIR := $(wildcard media)
ifeq ($(MEDIA_DIR),)
MEDIA_STREAMS :=
else
MEDIA_STREAMS := $(ROOTFS_DIR)/media/badapple.jmv $(ROOTFS_DIR)/media/caramel.jmv

$(MEDIA_STREAMS) &: tools/encode_media.py | $(BUILD)
	@command -v "$(FFMPEG)" >/dev/null || { echo "Missing FFmpeg ($(FFMPEG)). Install it or set FFMPEG=/path/to/ffmpeg.exe" >&2; exit 1; }
	mkdir -p $(ROOTFS_DIR)/media
	$(PYTHON) tools/encode_media.py --ffmpeg "$(FFMPEG)" --input-dir media --output-dir $(ROOTFS_DIR)/media
endif

$(ROOTFS): $(USER_PROGRAMS) $(MEDIA_STREAMS) $(ROOTFS_FILES) | $(BUILD)
	@test -d "$(ROOTFS_DIR)" || { echo "Missing $(ROOTFS_DIR) directory"; exit 1; }
	@files="$$(find "$(ROOTFS_DIR)" -type f -print -quit)" || exit 1; \
		test -n "$$files" || { echo "$(ROOTFS_DIR) contains no files"; exit 1; }
	rm -f $@
	tar --format=ustar -cf $@ -C $(ROOTFS_DIR) .

LOADER_CFLAGS := --target=x86_64-pc-win32-coff -std=c11 -ffreestanding \
                 -fno-stack-protector -fno-builtin -fno-exceptions \
                 -fno-asynchronous-unwind-tables -fno-unwind-tables \
                 -Wall -Wextra -Werror -O2 \
                 -DJCOS_FRAMEBUFFER_WIDTH=$(FRAMEBUFFER_WIDTH) \
                 -DJCOS_FRAMEBUFFER_HEIGHT=$(FRAMEBUFFER_HEIGHT)

KERNEL_CFLAGS := --target=x86_64-unknown-none-elf -std=c11 -ffreestanding \
                 -fno-stack-protector -fno-builtin -fpie -fno-plt \
                 -fvisibility=hidden -mno-red-zone -mgeneral-regs-only -mno-sse -mno-sse2 \
                 -fno-asynchronous-unwind-tables -fno-unwind-tables \
                 -Wall -Wextra -Werror -O2

USER_CFLAGS := --target=x86_64-unknown-none-elf -std=c11 -ffreestanding \
               -fno-stack-protector -fno-builtin -fpie -fno-plt \
               -fvisibility=hidden -mno-red-zone -mgeneral-regs-only -mno-sse -mno-sse2 \
               -fno-asynchronous-unwind-tables -fno-unwind-tables \
               -Wall -Wextra -Werror -O2

KERNEL_CPPFLAGS := -Ikernel -Ikernel/shell -Ikernel/tests -Iinclude
KERNEL_C_SOURCES := $(sort $(shell find kernel -type f -name '*.c'))
KERNEL_C_OBJECTS := $(patsubst %.c,$(BUILD)/%.o,$(KERNEL_C_SOURCES))
KERNEL_HEADERS := $(sort $(shell find kernel include -type f -name '*.h'))
NASM_PATH := $(shell command -v $(NASM) 2>/dev/null)

.PHONY: all binaries image media validate run run-headless inspect clean check-build-tools check-image-tools check-inspect-tools check-run-tools

all: check-image-tools $(IMAGE)
binaries: check-build-tools $(EFI) $(KERNEL)
image: check-image-tools $(IMAGE)
media: $(MEDIA_STREAMS)
check-build-tools:
	@command -v $(CLANG) >/dev/null || { echo "Missing $(CLANG). Run: pacman -S --needed mingw-w64-x86_64-clang"; exit 1; }
	@command -v $(LLD_LINK) >/dev/null || { echo "Missing $(LLD_LINK). Run: pacman -S --needed mingw-w64-x86_64-lld"; exit 1; }
	@command -v $(LD) >/dev/null || { echo "Missing $(LD). Run: pacman -S --needed mingw-w64-x86_64-lld"; exit 1; }
	@command -v $(READELF) >/dev/null || { echo "Missing $(READELF). Run: pacman -S --needed mingw-w64-x86_64-llvm-tools"; exit 1; }

check-image-tools: check-build-tools
	@command -v $(PYTHON) >/dev/null || { echo "Missing $(PYTHON). Run: pacman -S --needed mingw-w64-x86_64-python"; exit 1; }

check-inspect-tools: check-build-tools
	@command -v $(OBJDUMP) >/dev/null || { echo "Missing $(OBJDUMP). Run: pacman -S --needed mingw-w64-x86_64-llvm-tools"; exit 1; }

check-run-tools: check-image-tools
	@command -v $(QEMU) >/dev/null || { echo "Missing $(QEMU). Run: pacman -S --needed mingw-w64-x86_64-qemu"; exit 1; }

$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/loader.obj: loader/loader.c loader/uefi.h loader/elf.h include/boot_info.h | $(BUILD)
	$(CLANG) $(LOADER_CFLAGS) -c loader/loader.c -o $@

$(EFI): $(BUILD)/loader.obj
	MSYS2_ARG_CONV_EXCL='*' $(LLD_LINK) /subsystem:efi_application /entry:efi_main /nodefaultlib /machine:x64 \
	           /dynamicbase /nxcompat /out:$@ $^

ifneq ($(NASM_PATH),)
$(BUILD)/arch.o: kernel/arch.asm include/boot_info.h | $(BUILD)
	@echo "Using NASM: $(NASM_PATH)"
	$(NASM) -f elf64 kernel/arch.asm -o $@
else
$(BUILD)/arch.o: kernel/arch.S include/boot_info.h | $(BUILD)
	@echo "NASM not found; using equivalent Clang/GAS fallback kernel/arch.S"
	$(CLANG) --target=x86_64-unknown-none-elf -c -x assembler kernel/arch.S -o $@
endif

$(BUILD)/%.o: %.c $(KERNEL_HEADERS) | $(BUILD)
	mkdir -p $(dir $@)
	$(CLANG) $(KERNEL_CFLAGS) $(KERNEL_CPPFLAGS) -c $< -o $@

$(KERNEL): $(BUILD)/arch.o $(KERNEL_C_OBJECTS) kernel/linker.ld Makefile.msys2
	$(LD) -m elf_x86_64 -pie -Bsymbolic --no-dynamic-linker --no-undefined -nostdlib \
	      -T kernel/linker.ld -o $@ $(BUILD)/arch.o $(KERNEL_C_OBJECTS)
	$(CHECK_ELF_RELOCATIONS)

$(IMAGE): $(EFI) $(KERNEL) $(ROOTFS) tools/make_usb_image.py
	$(PYTHON) tools/make_usb_image.py $(EFI) $(KERNEL) $(ROOTFS) $(IMAGE)

validate: check-image-tools $(IMAGE) tools/validate_image.py
	$(PYTHON) tools/validate_image.py $(IMAGE) $(EFI) $(KERNEL) $(ROOTFS)

inspect: check-inspect-tools binaries
	@echo "=== EFI loader ==="
	$(OBJDUMP) -p $(EFI) | grep -E 'file format|Subsystem|reloc' || true
	@echo "=== kernel ELF ==="
	$(READELF) -h $(KERNEL) | grep -E 'Class:|Type:|Machine:|Entry point'
	$(READELF) -l $(KERNEL)
	$(READELF) -r $(KERNEL)
	@echo "=== important symbols ==="
	$(READELF) -s $(KERNEL) | grep -E '(_start|kernel_main|interrupt_dispatch|isr_stub_offsets)' || true

run: check-run-tools $(IMAGE) tools/run_qemu.sh
	OVMF_CODE="$(OVMF_CODE)" OVMF_VARS="$(OVMF_VARS)" tools/run_qemu.sh $(IMAGE)

run-headless: check-run-tools $(IMAGE) tools/run_qemu.sh
	OVMF_CODE="$(OVMF_CODE)" OVMF_VARS="$(OVMF_VARS)" tools/run_qemu.sh --headless $(IMAGE)

clean:
	rm -rf $(BUILD)
	rm -f $(USER_PROGRAMS)
