#ifndef JCOS_COMPOSITOR_SERVICE_PROTOCOL_H
#define JCOS_COMPOSITOR_SERVICE_PROTOCOL_H

#include "display_service_protocol.h"
#include "service_protocol.h"

#define JCOS_COMPOSITOR_SERVICE_PROTOCOL_VERSION JCOS_SERVICE_PROTOCOL_VERSION_1

#define JCOS_COMPOSITOR_SERVICE_OP_PING            1ULL
#define JCOS_COMPOSITOR_SERVICE_OP_SHUTDOWN        2ULL
#define JCOS_COMPOSITOR_SERVICE_OP_DIAG_FAULT      3ULL
#define JCOS_COMPOSITOR_SERVICE_OP_SURFACE_CONFIG  4ULL
#define JCOS_COMPOSITOR_SERVICE_OP_SURFACE_REMOVE  5ULL
#define JCOS_COMPOSITOR_SERVICE_OP_FOCUS_SURFACE   6ULL
#define JCOS_COMPOSITOR_SERVICE_OP_COMPOSE         7ULL

#define JCOS_COMPOSITOR_SERVICE_REPLY_PONG       0x434F4D50504F4E47ULL
#define JCOS_COMPOSITOR_SERVICE_REPLY_STOPPED    0x434F4D5053544F50ULL
#define JCOS_COMPOSITOR_SERVICE_REPLY_CONFIGURED 0x434F4D5043464721ULL
#define JCOS_COMPOSITOR_SERVICE_REPLY_REMOVED    0x434F4D50524D5621ULL
#define JCOS_COMPOSITOR_SERVICE_REPLY_FOCUSED    0x434F4D50464F4321ULL
#define JCOS_COMPOSITOR_SERVICE_REPLY_COMPOSED   0x434F4D50434D5021ULL

#define JCOS_COMPOSITOR_SERVICE_HEADER(op, version) \
    ((((version) & 0xFFFFFFFFULL) << 32) | ((op) & 0xFFFFFFFFULL))
#define JCOS_COMPOSITOR_SERVICE_HEADER_OP(header) ((header) & 0xFFFFFFFFULL)
#define JCOS_COMPOSITOR_SERVICE_HEADER_VERSION(header) (((header) >> 32) & 0xFFFFFFFFULL)

#endif