#ifndef JCOS_CONSOLE_SERVICE_PROTOCOL_H
#define JCOS_CONSOLE_SERVICE_PROTOCOL_H

#include "service_protocol.h"
#include "console_input_protocol.h"

#define JCOS_CONSOLE_SERVICE_PROTOCOL_VERSION JCOS_SERVICE_PROTOCOL_VERSION_1

#define JCOS_CONSOLE_SERVICE_MESSAGE_WRITE_BYTE 1ULL
#define JCOS_CONSOLE_SERVICE_MESSAGE_SHUTDOWN   2ULL

/* R7a.3 normal-shell control/input lives in Ring3. The kernel monitor owns only
 * the bounded handoff and emergency return path. */
#define JCOS_CONSOLE_SERVICE_MESSAGE_SHELL_ACTIVATE   0x10ULL
#define JCOS_CONSOLE_SERVICE_MESSAGE_SHELL_DEACTIVATE 0x11ULL
#define JCOS_CONSOLE_SERVICE_MESSAGE_SHELL_KEY_EVENT  0x12ULL
#define JCOS_CONSOLE_SERVICE_MESSAGE_SERVICE_RESULT    0x13ULL

/* Privileged transition into a single foreground application-output session.
 * Application payloads use console_client_protocol.h on a separate endpoint. */
#define JCOS_CONSOLE_SERVICE_MESSAGE_APP_SESSION_BEGIN 0x20ULL

#define JCOS_CONSOLE_SERVICE_MESSAGE_DIAGNOSTIC_FAULT 0x7FFFFFFFFFFFFF21ULL

#define JCOS_CONSOLE_SERVICE_REPLY_WRITTEN        0x8000000000000201ULL
#define JCOS_CONSOLE_SERVICE_REPLY_STOPPED        0x8000000000000202ULL
#define JCOS_CONSOLE_SERVICE_REPLY_SHELL_ACTIVE   0x8000000000000210ULL
#define JCOS_CONSOLE_SERVICE_REPLY_SHELL_INACTIVE 0x8000000000000211ULL
#define JCOS_CONSOLE_SERVICE_REPLY_KEY_HANDLED    0x8000000000000212ULL
#define JCOS_CONSOLE_SERVICE_REPLY_SERVICE_RESULT  0x8000000000000213ULL
#define JCOS_CONSOLE_SERVICE_REPLY_APP_SESSION_ACTIVE 0x8000000000000220ULL

/* Reply word 3 for SHELL_KEY_EVENT:
 *   low 32 bits  = shell action
 *   high 32 bits = command result (nonzero only for a submitted line). */
#define JCOS_CONSOLE_SHELL_ACTION_NONE           0ULL
#define JCOS_CONSOLE_SHELL_ACTION_RETURN_MONITOR 1ULL
#define JCOS_CONSOLE_SHELL_ACTION_RUN_FOREGROUND 2ULL
#define JCOS_CONSOLE_SHELL_ACTION_SERVICE_CONTROL 3ULL
#define JCOS_CONSOLE_SHELL_ACTION_RUN_GRAPHICS    4ULL

#define JCOS_CONSOLE_SHELL_RESULT_NONE    0ULL
#define JCOS_CONSOLE_SHELL_RESULT_OK      1ULL
#define JCOS_CONSOLE_SHELL_RESULT_UNKNOWN 2ULL
#define JCOS_CONSOLE_SHELL_RESULT_EMPTY   3ULL

#define JCOS_CONSOLE_SERVICE_PACK_SERVICE_RESULT(result, state) \
    ((((state) & 0xFFFFULL) << 48) | ((result) & 0x0000FFFFFFFFFFFFULL))
#define JCOS_CONSOLE_SERVICE_UNPACK_SERVICE_STATE(value) (((value) >> 48) & 0xFFFFULL)
#define JCOS_CONSOLE_SERVICE_UNPACK_SERVICE_RESULT(value) ((value) & 0x0000FFFFFFFFFFFFULL)

#define JCOS_CONSOLE_SHELL_PACK_RESULT(action, result) \
    ((((result) & 0xFFFFFFFFULL) << 32) | ((action) & 0xFFFFFFFFULL))
#define JCOS_CONSOLE_SHELL_UNPACK_ACTION(value) ((value) & 0xFFFFFFFFULL)
#define JCOS_CONSOLE_SHELL_UNPACK_RESULT(value) (((value) >> 32) & 0xFFFFFFFFULL)

#endif
