#ifndef JCOS_INPUT_ECHO_ABI_H
#define JCOS_INPUT_ECHO_ABI_H

#define JCOS_INPUT_ECHO_APP_PATH "/bin/inputecho.elf"
#define JCOS_INPUT_ECHO_EXPECTED_CHARACTER 'K'
#define JCOS_INPUT_ECHO_TEXT "INPUT K SHIFT ALT"
#define JCOS_INPUT_ECHO_INVALID_TEXT "INPUT EVENT INVALID"

#endif
