#ifndef JCOS_SUPERVISOR_PROTOCOL_H
#define JCOS_SUPERVISOR_PROTOCOL_H

#define SUPERVISOR_MESSAGE_PING 1ULL
#define SUPERVISOR_MESSAGE_SHUTDOWN 2ULL

/* Kernel-authorized R6 diagnostics. These are intentionally not application
 * service-management APIs; only the kernel owns the command SEND authority. */
#define SUPERVISOR_MESSAGE_DIAGNOSTIC_ARM_SHUTDOWN_HANG 0x7FFFFFFFFFFFFF01ULL
#define SUPERVISOR_MESSAGE_DIAGNOSTIC_FAULT             0x7FFFFFFFFFFFFF02ULL

#define SUPERVISOR_REPLY_PONG 0x8000000000000001ULL
#define SUPERVISOR_REPLY_STOPPED 0x8000000000000002ULL
#define SUPERVISOR_REPLY_DIAGNOSTIC_ARMED 0xFFFFFFFFFFFFFF01ULL

#endif